# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('vat_payer', models.BooleanField()),
                ('vat_number', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('amount_total', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=30)),
            ],
        ),
    ]
