# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('amount_total', models.IntegerField()),
                ('comment', models.TextField()),
                ('type', models.CharField(choices=[('customer', 'Partner'), ('supplier', 'Supplier')], default='customer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=40)),
                ('invoice_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('vat_payer', models.BooleanField()),
                ('vat_number', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('customer', models.BooleanField(default=True)),
                ('supplier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('partner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Partner')),
                ('employee_count', models.IntegerField(default=1)),
            ],
            bases=('webapp.partner',),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product_id',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='webapp.Product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Partner'),
        ),
    ]
