# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=40)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.InvoiceCustomer')),
            ],
        ),
    ]
