# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='internal_reference',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=20),
        ),
    ]
