# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecustomer',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Customer'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product_id',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='webapp.Product'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.InvoiceCustomer'),
        ),
    ]
