# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20161210_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
