# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161210_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 19, 35, 20, 522527, tzinfo=utc), verbose_name='Date'),
        ),
    ]
