# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20161210_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 21, 8, 15, 726160, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
