# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20161210_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_total',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.TextField(default='Enter comment here...'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 21, 18, 13, 257174, tzinfo=utc), verbose_name='Date'),
        ),
    ]
