# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20161210_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 21, 24, 45, 438831, tzinfo=utc), verbose_name='Date'),
        ),
    ]
