# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20161210_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 22, 5, 45, 669592, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='webapp.Tax'),
        ),
    ]
