# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20161210_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('percent', 'Percentage')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 22, 8, 21, 621039, tzinfo=utc), verbose_name='Date'),
        ),
    ]
