# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20161210_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('contact', 'Contact'), ('invoice', 'Invoice'), ('shipping', 'Shipping')], max_length=10, verbose_name='Address Type')),
                ('street', models.CharField(blank=True, max_length=40, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=15, verbose_name='Zip')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Partner')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 23, 18, 55, 671507, tzinfo=utc), verbose_name='Date'),
        ),
    ]
