# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20161210_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 0, 4, 4, 397203, tzinfo=utc), verbose_name='Date'),
        ),
    ]
