# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20161211_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 17, 56, 10, 741220, tzinfo=utc), verbose_name='Date'),
        ),
    ]
