# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20161214_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 8, 1, 2, 682825, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
